In [5]:
import pandas as pd     

df = pd.DataFrame({
    'u': [10.0, 20.0, 10.0], 'g': [10.0, 20.0, 10.0], 'r': [10.0, 20.0, 10.0],
    'i': [10.0, 20.0, 10.0], 'z': [10.0, 20.0, 10.0], 'redshift': [0.0, 2.5, 0.0],
    'class': ['STAR', 'GALAXY', 'QSO']
})

class_map = {'STAR': 0, 'GALAXY': 1, 'QSO': 2}
    # ==========================
    
    # 1. Apply class mapping to 'class' column
# df['class'] = df['class'].map(class_map)
print(df)
df=df.replace(class_map)
c=df['class']
print(df)
print(df[df['class']==1])
print(df['class']==1)
# print(c,c.values)  


      u     g     r     i     z  redshift   class
0  10.0  10.0  10.0  10.0  10.0       0.0    STAR
1  20.0  20.0  20.0  20.0  20.0       2.5  GALAXY
2  10.0  10.0  10.0  10.0  10.0       0.0     QSO
      u     g     r     i     z  redshift  class
0  10.0  10.0  10.0  10.0  10.0       0.0      0
1  20.0  20.0  20.0  20.0  20.0       2.5      1
2  10.0  10.0  10.0  10.0  10.0       0.0      2
      u     g     r     i     z  redshift  class
1  20.0  20.0  20.0  20.0  20.0       2.5      1
0    False
1     True
2    False
Name: class, dtype: bool


/var/folders/jc/8r_cxn9j5fncd5rm5gd545q80000gn/T/ipykernel_5080/2749418705.py:15: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace(class_map)


In [ ]:
feature_cols = ['u', 'g', 'r', 'i', 'z', 'redshift']
# print(df)

arr=df.values
print(arr)
arr[1:3]



[[10.  10.  10.  10.  10.   0.   0. ]
 [20.  20.  20.  20.  20.   2.5  1. ]
 [10.  10.  10.  10.  10.   0.   2. ]]


array([[20. , 20. , 20. , 20. , 20. ,  2.5,  1. ],
       [10. , 10. , 10. , 10. , 10. ,  0. ,  2. ]])

In [11]:
import numpy as np

# 模拟训练集标签（一维，N=5）
y_train = np.array([10, 20, 30, 40, 50])  # shape: (5,)

# 模拟k_indices（二维，M=2个测试样本，k=3个近邻）
k_indices = np.array([
    [0, 2, 4],  # 第1个测试样本的3个近邻索引：0、2、4
    [1, 3, 0]   # 第2个测试样本的3个近邻索引：1、3、0
])  # shape: (2, 3)

# 用二维索引取一维数组的值
k_neighbor_labels = y_train[k_indices]
print(k_neighbor_labels)
# 输出：
# [[10 30 50]
#  [20 40 10]]
print(k_neighbor_labels.shape)  # 输出：(2, 3) → 和k_indices形状一致！

print(np.bincount(y_train))

[[10 30 50]
 [20 40 10]]
(2, 3)
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 1]
