In [3]:
import pandas as pd

In [4]:
def load_n_filter(file_name, features):
    # TODO: Load your downloaded CSV
    df=pd.read_csv(file_name)

    # TODO: Keep only songs with popularity >= 80
    df_filtered=df[df['popularity']>=80]

    # TODO: Select the 3 audio features for clustering and drop any rows with missing values
    df_filtered=df_filtered[features]
    df_filtered=df_filtered.dropna()

    return df_filtered

if __name__ == "__main__":
    features = ['danceability', 'energy', 'tempo']
    df_popular = load_n_filter('spotify_2015_2025_85k.csv', features)
    # Convert to NumPy array
    X = df_popular.to_numpy()

    print(f"Number of popular songs (popularity ≥ 80): {X.shape[0]}")
    print(f"Clustering on {X.shape[1]} audio features")
    # print(df_popular.info())

Number of popular songs (popularity ≥ 80): 2971
Clustering on 3 audio features


In [5]:
import pandas as pd

df = pd.DataFrame({
    'age':    [20, 30, 40],
    'income': [40000, 50000, 60000]
})
nn=df.values
n=df.to_numpy()

mean = nn.mean(axis=0)
print(df.mean(axis=0))
print(mean)

age          30.0
income    50000.0
dtype: float64
[3.e+01 5.e+04]


In [6]:
import pandas as pd
import numpy as np

data = {'A': [1, 2, np.nan, 4], 
        'B': [5, np.nan, np.nan, 8], 
        'C': [9, 10, 11, 12]}
df = pd.DataFrame(data)

# Remove all rows that contain at least one NaN value
print(df)
df_cleaned = df.dropna()
print(df_cleaned)


     A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  NaN  11
3  4.0  8.0  12
     A    B   C
0  1.0  5.0   9
3  4.0  8.0  12


In [12]:
X=n
k=2
n_samples = X.shape[0]
# Randomly select k unique indices from 0 to n_samples-1
random_indices = np.random.choice(n_samples, size=k, replace=False)
# Use indices to pick centroids from X
centroids = X[random_indices]

print(X)
print()
print(centroids)

X[[True,True,False]]


[[   20 40000]
 [   30 50000]
 [   40 60000]]

[[   40 60000]
 [   30 50000]]


array([[   20, 40000],
       [   30, 50000]])

In [13]:
def fun():
    print(121)
    return 1

d=fun()
print(d)

121
1
