In [9]:
print(y)

100


In [8]:
y=100

In [11]:
import numpy as np

ytrain=[0,0,1,2,1]
size=len(ytrain)
class_priors=np.unique(ytrain)
print(class_priors,type(class_priors))

re=class_priors.reshape(-1,1)
pro=re-ytrain

pro=np.sum(pro==0,axis=1)/size
print(pro)


[0 1 2] <class 'numpy.ndarray'>
[0.4 0.4 0.2]


In [26]:
arr=np.array([1,0,1,1,0])
change=arr[:, np.newaxis]
cha2=arr[np.newaxis,:]
unique=np.unique(arr)[:, np.newaxis]
# print(unique)
# print(arr==unique)

# print(unique==arr)
print(cha2)
print(cha2+[1,2,3,2,1])

[[1 0 1 1 0]]
[[2 2 4 3 1]]
